def fixture(name)
  cookbook name, path: "test/fixtures/cookbooks/#{name}"
end

source 'https://supermarket.chef.io'

metadata

group :integration do
  cookbook 'arcgis-enterprise', path: '../arcgis-enterprise'
  cookbook 'arcgis-repository', path: '../arcgis-repository'
end

