def fixture(name)
  cookbook name, path: "test/fixtures/cookbooks/#{name}"
end

source 'https://supermarket.chef.io'

metadata

group :integration do
  cookbook 'aws'
  cookbook 'seven_zip'
  fixture 'download-setups-s3'
end
