def fixture(name)
  cookbook name, path: "test/fixtures/cookbooks/#{name}"
end

source 'https://supermarket.chef.io'

metadata

group :integration do
  cookbook 'arcgis-repository', path: '../arcgis-repository'
  cookbook 'arcgis-enterprise', path: '../arcgis-enterprise'
  cookbook 'apt'
  cookbook 'aws'
  cookbook 'postgresql'
  cookbook 'seven_zip'
  cookbook 'tar'
  fixture  'download-setups-s3'
  fixture  'postgresql-test'
end
