name             'arcgis-server'
maintainer       'Esri'
maintainer_email 'contracts@esri.com'
license          'Apache 2.0'
description      'Installs and configures ArcGIS Web GIS and Server GIS'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '2.3.0'
chef_version     '>= 12.5.1', '< 13.0' if defined? chef_version

depends          'hostsfile'
depends          'limits'
depends          'authbind'
depends          'iptables'
depends          'windows'
depends          'openssl'
depends          'ms_dotnet'

supports         'windows'
supports         'ubuntu'
supports         'redhat'

recipe 'arcgis-server::clean', 'Deletes local directories created by ArcGIS software'
recipe 'arcgis-server::datastore', 'Installs and configures ArcGIS Data Store on primary machine'
recipe 'arcgis-server::datastore_standby', 'Installs and configures ArcGIS Data Store on standby machine'
recipe 'arcgis-server::disable_geoanalytics', 'Resets the big data analytics configuration on ArcGIS Portal'
recipe 'arcgis-server::egdb', 'Registers GeoDatabases with server'
recipe 'arcgis-server::enable_geoanalytics', 'Configures the ArcGIS Portal to perform big data analytics'
recipe 'arcgis-server::federation', 'Federates ArcGIS Server with Portal for ArcGIS'
recipe 'arcgis-server::fileserver', 'Configures shared directories on file server machine'
recipe 'arcgis-server::hosts', 'Creates entries in /etc/hosts file for the specified hostname to IP address map'
recipe 'arcgis-server::iis', 'Enables required IIS features and configures HTTPS binding'
recipe 'arcgis-server::iptables', 'Configures ports for products'
recipe 'arcgis-server::ip-install', 'Installs language packs for ArcGIS Enterprise software'
recipe 'arcgis-server::portal', 'Installs and configures Portal for ArcGIS on primary machine'
recipe 'arcgis-server::portal_stanby', 'Installs and configures Portal for ArcGIS on standby machine'
recipe 'arcgis-server::portal_wa', 'Installs Web Adaptor and configures it with Portal for ArcGIS'
recipe 'arcgis-server::server', 'Installs and configures ArcGIS Server'
recipe 'arcgis-server::server_node', 'Installs ArcGIS Server on the machine and joins an existing site'
recipe 'arcgis-server::server_wa', 'Installs Web Adaptor and configures it with ArcGIS Server'
recipe 'arcgis-server::services', 'Publishes services to ArcGIS Server'
recipe 'arcgis-server::system', 'System requirements'
recipe 'arcgis-server::webgis_installed', 'Installs Server, Data Store, Portal, and Web Adaptors for Server and Portals'
recipe 'arcgis-server::webgis_uninstalled', 'Uninstalls all ArcGIS software of the specified version'
recipe 'arcgis-server::webgis_validate', 'Checks if ArcGIS for Server setups and authorization files exist'

