# frozen_string_literal: true

source 'https://supermarket.chef.io'

metadata

group :release do
  cookbook 'arcgis-desktop', path: '../arcgis-desktop'
  cookbook 'arcgis-egdb', path: '../arcgis-egdb'
  cookbook 'arcgis-enterprise', path: '../arcgis-enterprise'
  cookbook 'arcgis-geoevent', path: '../arcgis-geoevent'
  cookbook 'arcgis-notebooks', path: '../arcgis-notebooks'
  cookbook 'arcgis-insights', path: '../arcgis-insights'
  cookbook 'arcgis-pro', path: '../arcgis-pro'
  cookbook 'arcgis-repository', path: '../arcgis-repository'
  cookbook 'esri-iis', path: '../esri-iis'
  cookbook 'esri-tomcat', path: '../esri-tomcat'
  cookbook 'apt'
end
