source 'https://supermarket.chef.io'

metadata

cookbook 'hostsfile', '~> 2.4'
cookbook 'limits', '~> 1.0'
cookbook 'authbind', '~> 0.1'
cookbook 'iptables', '~> 1.0'
cookbook 'windows', '~> 1.39'
cookbook 'openssl', '~> 4.0'
cookbook 'esri-tomcat', path: '../esri-tomcat'
cookbook 'esri-iis', path: '../esri-iis'
cookbook 'tomcat', path: '../tomcat'
cookbook 'yum-epel', path: '../yum-epel'
cookbook 'java'
cookbook 'nfs'
